# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3c59d6248acd81a2b8fc3334a7d8daf9e128dab93a1ceaf92f0e8f0c92ec048a34ac8c96433f0b386716036eac8921b790e5bdf8d6296eac48dee964537c4a1

test:
  secret_key_base: c8374f77e8d32642fd2e345b42bfa80e8a5896ce0f58c25cffad6ddcd982bc4307ff2d86bf40937818b98ee7dd14114edf52ae4b2d103fcac5e0822df2a26e82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
